ignore:
  - "addkernels/"
  - "build/"
  - "driver/"
  - "test/"
comment:                  # this is a top-level key
  layout: "reach, diff, flags, files"
  behavior: default
  require_changes: false  # if true: only post the comment if coverage changes
  require_base: no        # [yes :: must have a base report to post]
  require_head: no       # [yes :: must have a head report to post]

coverage:
  status:
    project:
      default:
        target: auto
        threshold: 1%
        if_ci_failed: error
        informational: false
        only_pulls: false