FROM rocm/miopen:ci 

ARG DEBIAN_FRONTEND=noninteractive

RUN apt update && \
	apt install -y --no-install-recommends \
		fish

WORKDIR /
RUN git clone --recurse-submodules https://github.com/ROCmSoftwarePlatform/gputt.git && \
	cd gputt && mkdir build && cd build && cmake -DCMAKE_CXX_COMPILER=hipcc .. && \
	make VERBOSE=1 && make install && \
	cd / && rm -rf gputt

